### ISSUE TITLE
Fail to build on Windows

### ISSUE THREAD

**Issue by tan-wei** [MindFlavor/tormov#2]
It's quite a useful tool for me, thanks very much. However, it fails on Windows because of simlink. Is any plan to work with Windows? Thanks!
Version:
  - rustc 1.43.0-nightly (61d9231ff 2020-02-15)
  - toolchain nightly-x86_64-pc-windows-msvc
Error message:
```
   Compiling tormov v0.2.2
error[E0433]: failed to resolve: could not find `unix` in `os`
   --> C:\Users\Winterreise\.cargo\registry\src\github.com-1ecc6299db9ec823\tormov-0.2.2\src\main.rs:130:22
    |
130 |             std::os::unix::fs::symlink(from, to)
    |                      ^^^^ could not find `unix` in `os`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
error: failed to compile `tormov v0.2.2`, intermediate artifacts can be found at `C:\Users\WINTER~1\AppData\Local\Temp\cargo-installesr7dG`

Caused by:
  could not compile `tormov`.

To learn more, run the command again with --verbose.
```

**Comment by MindFlavor** [comment]
It should not be difficult to add Windows support (even though Windows links are a bit different). I'll give it a whirl and get back to you!

**Comment by tan-wei** [comment]
Got it. Thanks for your rapid reply.

**Comment by MindFlavor** [comment]
The code compiles but I haven't tested its functionality. If need be please reopen this issue/open another one!
